# Generated by Django 4.0.2 on 2022-05-09 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aid', models.CharField(max_length=20)),
                ('Aname', models.CharField(max_length=50)),
                ('Atype', models.CharField(max_length=50)),
                ('Adestination', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'AssetRegistration',
            },
        ),
    ]
